- Documentation/FluidTemplates/Index.rst
Add a short section about the `Private/Language` folder. Please review it.
> Add "Language" to private folders section

- Documentation/ExtensionConfiguration/Index.rst
- Documentation/ExtensionInstallation/Index.rst
- Documentation/MainMenuCreation/Index.rst
Found a few small typos and updated some sentences to improve readability.
> Typos and minor changes to sentence structure

- Documentation/Summary/Index.rst
The extension-code is available on Github meanwhile. Update the URL.
> Add link to the site_package-code

- Documentation/ExtensionConfiguration/Index.rst
- Documentation/Index.rst
- Documentation/Introduction/Index.rst
- Documentation/Preface/Index.rst
- Documentation/Settings.cfg
- Documentation/Summary/Index.rst
- Documentation/Targets.rst
- README.rst
- composer.json
> Change spelling for sitepackage

- Documentation/ContentMapping/Index.rst
Feature: #82812 - New syntax for importing TypoScript files
Feature: #78161 - Introduce .typoscript file extension
> Modernize TypoScript snippets (#82812 & #78161)

- Documentation/ContentMapping/Index.rst
- Documentation/TypoScriptConfiguration/Index.rst
* Change <INCLUDE_TYPOSCRIPT: ... > to @import '...'
This was already done in some point of the code. I updated some other places and update the documentation.
> Fix issue with differences in documentation

- Documentation/ContentMapping/Index.rst
Related #47 
Back port also to 10 and 9 please.
> Add link to Backend layout page

- Documentation/ExtensionConfiguration/Index.rst
- Documentation/ExtensionInstallation/Index.rst
- Documentation/ExtensionInstallation/InstallationWithoutComposer.rst
instead of a legacy non-composer project directly on a webserver.
> [FEATURE] Promote developing with composer and locally on ddev

- Documentation/ContentMapping/Index.rst
- Documentation/Summary/Index.rst
>  [FEATURE] display content with data processors

- Documentation/CodeSnippets/ExtensionConfiguration/ComposerJson.rst.txt
- Documentation/CodeSnippets/ExtensionConfiguration/ExtEmconf.rst.txt
- Documentation/CodeSnippets/ExtensionConfiguration/TcaOverridePages.rst.txt
- Documentation/CodeSnippets/ExtensionConfiguration/TcaOverrideSysTemplate.rst.txt
- Documentation/CodeSnippets/Fluid/Layout.rst.txt
- Documentation/CodeSnippets/Fluid/PartialJumbotron.rst.txt
- Documentation/CodeSnippets/Fluid/StaticHtml.rst.txt
- Documentation/CodeSnippets/Fluid/Step1Default.rst.txt
- Documentation/CodeSnippets/Fluid/Step2Default.rst.txt
- Documentation/CodeSnippets/Fluid/Step3Default.rst.txt
- Documentation/CodeSnippets/Fluid/TemplateDefault.rst.txt
- Documentation/CodeSnippets/Fluid/TemplateTwoColumns.rst.txt
- Documentation/CodeSnippets/TypoScript/Constants.rst.txt
- Documentation/CodeSnippets/TypoScript/Page.rst.txt
- Documentation/CodeSnippets/TypoScript/Part1FluidTemplateSection.rst.txt
- Documentation/CodeSnippets/TypoScript/Part2CssFileInclusion.rst.txt
- Documentation/CodeSnippets/TypoScript/Part4GlobalConfiguration.rst.txt
- Documentation/CodeSnippets/TypoScript/Part5MenuProcessor.rst.txt
- Documentation/CodeSnippets/TypoScript/Setup.rst.txt
- Documentation/ExtensionConfiguration/Index.rst
- Documentation/FluidTemplates/Index.rst
- Documentation/MainMenuCreation/Index.rst
- Documentation/TypoScriptConfiguration/Index.rst
- screenshots.json
and replace code snippets with those automatically generated from the extension.
> [TASK] Update some chapters

- Documentation/ExtensionConfiguration/Index.rst
update info on ext_emconf.php
refs #64
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449
releases: master, 11.5
> [FEATURE] Move composer.json to top,

- Documentation/FluidTemplates/Index.rst
> [BUGFIX] Correct file path to templates

- Documentation/FluidTemplates/Index.rst
refs https://github.com/TYPO3-Documentation/T3DocTeam/issues/170
releases: 10.4, 9.5, 8.7
> [TASK] Remove old wiki links

- Documentation/ExtensionConfiguration/Index.rst
- Documentation/FluidTemplates/Index.rst
- Documentation/Settings.cfg
- remove duplicate label "directory-structure"
See #79 for details.
> [TASK] Fix rendering warnings

- Documentation/CodeSnippets/ExtensionConfiguration/TcaOverridePages.rst.txt
- Documentation/ContentMapping/Index.rst
- Documentation/Settings.cfg
On working in the changes regarding TYPO3 12 I noted it was not really explained for 11.5 either
> [FEATURE] Explain how to include page TSconfig

- Documentation/ContentMapping/Index.rst
- Documentation/DesignTemplate/Index.rst
- Documentation/ExtensionInstallation/Index.rst
- Documentation/FluidTemplates/Index.rst
- Documentation/MainMenuCreation/Index.rst
- Documentation/TypoScriptConfiguration/Index.rst
to make it more clear where code should go
Releases: main, 11.5
> [TASK] Add captions to code-blocks

- Documentation/ExtensionInstallation/Index.rst
- Documentation/ExtensionInstallation/InstallationWithoutComposer.rst
> Include legacy installation in the menu

- Documentation/FluidTemplates/MoreInformation/Index.rst
- Documentation/Settings.cfg
> [TASK] Remove references to the extbase book

- Documentation/ExtensionInstallation/Index.rst
resolves: https://typo3.slack.com/archives/C028JEPJL/p1696320747504609
releases: main
Remark: I changed all the files in the Sitepackage Tutorial, where I found "local_packages" and changed it to "packages" via the Slack Thread.
> Renaming local_packages to packages

- Documentation/Includes.rst.txt
> [TASK] Include disclaimer about TYPO3 version

- Documentation/FluidTemplates/Index.rst
> Adapt paths to the new directory structure in chapter Fluid template

- Documentation/ExtensionConfiguration/Index.rst
- Documentation/Summary/Index.rst
References: #179, #180
Releases: main
> Remove constants.typoscript

- Documentation/Index.rst
> [TASK] Correct card content of "create pages"

- Documentation/MinimalExample/Index.rst
- Documentation/MinimalExample/_config.yaml
to prevent confusion
Releases: main
> [TASK] Use the same site set all through the docs

- Documentation/Introduction/Index.rst
The advanced topics have been moved to
TYPO3 explained and are linked from here.
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage/issues/184
Releases: main, 12.4
> [TASK] Write a basic introduction page

- Documentation/Includes.rst.txt
> [TASK] Add end of life hint

- Documentation/Includes.rst.txt
> [TASK] Remove unused content in Includes.rst.txt

- Documentation/CodeSnippets/ExtensionConfiguration/ComposerJson.rst.txt
- Documentation/CodeSnippets/Fluid/PartialContent.rst.txt
- Documentation/ContentMapping/Index.rst
- Documentation/ContentMapping/_codesnippets/_SectionMainRender.diff
References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1140
>  Improve example for rendering record objects in PAGEVIEW

- Documentation/Assets/Index.rst
- Documentation/ContentMapping/AddContent.rst
- Documentation/ContentMapping/Index.rst
- Documentation/ContentMapping/SubpageLayout.rst
- Documentation/CreatePages/Index.rst
- Documentation/ExtensionConfiguration/Index.rst
- Documentation/ExtensionInstallation/Index.rst
- Documentation/FluidTemplates/Index.rst
- Documentation/Introduction/Index.rst
- Documentation/MainMenuCreation/Index.rst
- Documentation/MinimalExample/Index.rst
- Documentation/SiteSets/Index.rst
- Documentation/Summary/Index.rst
- Documentation/TypoScript/Index.rst
> [TASK] Add contents menu to pages

- Documentation/Assets/Index.rst
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage/issues/207
> [TASK] Hint at symlink creation in Copy assets chapter

- Documentation/Prerequisites/Index.rst
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage/issues/188
> [TASK] Link basic TYPO3 concepts in prerequisites

- Documentation/CodeSnippets/ExtensionConfiguration/ComposerJson.rst.txt
- Documentation/CodeSnippets/Fluid/PartialContent.rst.txt
- Documentation/ContentMapping/Index.rst
- Documentation/ContentMapping/_codesnippets/_SectionMainRender.diff
References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1148
> [TASK] cObject retrieves raw record automatically

- Documentation/Prerequisites/Index.rst
> Update TYPO3 version to stable release

- Documentation/MinimalExample/Index.rst
> Fix wrong site-package folder name

- Documentation/MinimalExample/Index.rst
> Update vendor/package name

- Documentation/ExtensionInstallation/Index.rst
> Update vendor\package name and TYPO3 version

- Documentation/ContentMapping/Index.rst
> [TASK] Adjust links to tsconfig reference

- Documentation/Assets/Index.rst
> [TASK] Do not copy assets, just explain those assets already there

- Documentation/ContentElementRendering/Index.rst
- Documentation/FluidTemplates/FromTheScratch.rst
- Documentation/FluidTemplates/Index.rst
> [TASK] Update Page View section

- .github/workflows/apply-precommit.yml
- .pre-commit-config.yaml
> [TASK] Automatically remove whitespace

- Documentation/ContentMapping/TypoScript.rst
> Fix indentation

- Documentation/Index.rst
- Documentation/Menu/Breadcrumb.rst
- Documentation/Menu/Index.rst
> [TASK] Adjust menu chapter for site package builder

- Documentation/Faq/Index.rst
- Documentation/FluidTemplates/FromTheScratch.rst
- Documentation/Index.rst
- Documentation/MinimalExample/Index.rst
- Documentation/NextSteps/Index.rst
- Documentation/_Includes/_DownloadSitePackage.rst.txt
> [TASK] Remove download option, link to builder

- .pre-commit-config.yaml
> [TASK] Exclude code snippets from pre-commit-hooks

- Documentation/Menu/Breadcrumb.rst
- Documentation/Menu/Index.rst
- Documentation/Menu/MetaMenu.rst
> [TASK] Document Footer menu

- Documentation/CodeSnippets/_settings.yaml
- Documentation/ContentElementRendering/Index.rst
- Documentation/SiteSets/Index.rst
References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1273
> [BUGFIX] Store and process site settings.yaml as a map
