TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage

Documentation/ContentMapping/Index.rst, Documentation/ExtensionInstallation/Index.rst, Documentation/FluidTemplates/Index.rst, Documentation/Introduction/Index.rst, Documentation/MainMenuCreation/Index.rst, Documentation/Preface/Index.rst
This commit removes the use of the word "so-called" and contains ajustments to the effected sentances. The word so-called is being used to introduce new names and concepts, this is the incorrect use of the word. The [Cambridge Dictonary](https://dictionary.cambridge.org/dictionary/english/so-called) features two examples of the word being used and its correct use. This commit also features minor ammendments to some introductary paragraphs.
[-]  Remove the word "so-called" where required
[+] Ammend the introduction paragraph in /Preface/
=> Adjust the use of the word "so-called" in sentences 

Documentation/TypoScriptConfiguration/Index.rst
Fix a critical typo in TypoScriptConfiguration/Index.rst
=> fix: critical typo

Documentation/FluidTemplates/Index.rst
I was struggling in the part "The Page Layout File" (line 238) - because after removing tags in the Default.html, the Default.html was empty, but the text suggested me, that there should still be some html inside. So I was a little bit confused and started to search, if I missed a download or sth. like that. The text now should, hopefully, point out that using the origin index.html, renamed to Default.html, is empty after removing all tags. Nevertheless there could be the second way, if using a custom Default.html, than some html will be left, after removing the mentioned tags. Hope you know what I mean :-)
Greetings, Diana Behr
=> Clearify changes made in Default.html

Documentation/ExtensionConfiguration/Index.rst
In the 'Directory and File Structure' section in the list in the code block the file "site_package/Resources/Public/Css/website.js" should be corrected to "site_package/Resources/Public/Css/website.css".
=> Small error in file name

Documentation/TypoScriptConfiguration/Index.rst
These properties were removed from core and serve no purpose anymore.
=> Remove unused ts configuration from example code

Documentation/ExtensionConfiguration/Index.rst
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92947-DeprecateTYPO3_MODEAndTYPO3_REQUESTTYPEConstants.html
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
=> [TASK] Remove TYPO3_REQUESTTYPE and TYPO3_MODE

Documentation/Summary/Index.rst
=> Replace Google links with reference to TYPO3 docs

Documentation/FluidTemplates/Index.rst
Somehow, the folder for language files (`Resources/Private/Language/`) is named in singular while most other folders are named plural only.
=> Folder for language files is in singular

Documentation/ExtensionConfiguration/Index.rst
The position of extension icon is, according to the tutorial, under "site_package/Resources/Public/Icons/Extension.svg".
=> New position of the extension icon

Documentation/ExtensionConfiguration/Index.rst, Documentation/FluidTemplates/Index.rst, Documentation/Introduction/Index.rst, Documentation/Settings.cfg
- remove duplicate label "directory-structure"
- update outdated label "t3security:start"
See #79 for details.
=> [TASK] Fix rendering warnings

Documentation/Introduction/Index.rst
This fixes a problem of not being able to link to this section.
=> Fix typo in section label

Documentation/MinimalExample/Index.rst
If you use composer, the composer config shown in "extension installation" is insufficient. You have to provide the extension key at least. Otherwise your site package extension will be missing. => Added reference to "extension configuration" which has a perfect example.
Also fixed the template file's path.
=> MinimalExample: Fixed path. +Composer config ref

Documentation/FluidTemplates/Index.rst
There are both singular and plural for the folder name 'Language' and 'Languages' respectively. I think the singular would be correct here.
=> Changed 2 × 'Languages' in 'Language'

Documentation/FluidTemplates/Index.rst
There are both singular and plural for the folder name 'Language' and 'Languages' respectively. I think the singular would be correct here.
=> Changed 2 × 'Languages' in 'Language' (#121)

Documentation/Introduction/Index.rst
Nowadays, RealURL should not be used in 'most' TYPO3 installations ;) Found in the section: Dependency Management
Releases: main, 12.4, 11.5
=> Remove RealURL from list of mentioned extensions (#134)

Documentation/ExtensionConfiguration/Index.rst, Documentation/ExtensionInstallation/Index.rst, Documentation/Index.rst, Documentation/Introduction/Index.rst, Documentation/MinimalExample/Index.rst
=> Overhaul Site Package tutorial

Documentation/guides.xml
This way the suggested interlinks when clicking on a title show the correct interlink
=> [TASK] Put default interlink shortcode

Documentation/ExtensionConfiguration/Index.rst
After:
Before:
releases: main, 12.4
=> [TASK] Use directory tree do display common sitepackage file structure

Documentation/guides.xml
Site package are two words. We currently have it in one word in the manual title but in two words title on the startpage etc
Releases: main, 13.4, 12.4
=> [TASK] Unify Site Package Tutorial title

Documentation/MinimalExample/Index.rst
Resolves https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage/issues/206 Releases: main, 13.4
=> Make  Installation of site-package more clear

Documentation/CodeSnippets/ExtensionConfiguration/ComposerJson.rst.txt, Documentation/CodeSnippets/Fluid/PartialJumbotron.rst.txt, Documentation/CodeSnippets/Fluid/TemplateDefault.rst.txt, Documentation/ContentMapping/Jumbotron.rst
=> [TASK] Update chapter on jumbotron for TYPO3 13.4

Documentation/MinimalExample/Index.rst
Adding info that you have to add the composer repository first, before installing sitepackage
=> Adding info about composer repository

Documentation/MinimalExample/Index.rst
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage/issues/290
=> [TASK] Make extension name, composer name and package name more clear

Documentation/ContentMapping/Index.rst, Documentation/ContentMapping/TypoScript.rst, Documentation/Index.rst, Documentation/MainMenuCreation/Index.rst
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage/issues/290
=> [TASK] Move splitting up TypoScript
